### ISSUE TITLE
Two fairly major issues.

### ISSUE THREAD

**Issue by varkarrus** [clickerultimate/clickerultimate.github.io#7]
1) Maxed Resources Still Drain.

When I've hit the cap for a certain resource, the resource producers still drain things. This is pretty annoying; once I've maxed out iron, my foundries should stop consuming stone.

2) No way to sell workers or buildings

Another annoying one since I couldn't predict in advance the tax / property tax mechanic. Some workers barely help out and I'd gladly dispose of them so that I can get gold easier. There's also the fact that, when I hit the Dark Ages, I had so much water consumers that I was barely making any water at all! It was a bit of a rough patch and, aside from going in better prepared, there was little I could do.

**Comment by clickerultimate** [comment]
Hello! Thank you for the feedback.

_Maxed Resources Still Drain_
This is intentional with the design of the game and therefore will not be changed for now.

_No way to sell workers or buildings_
This is fair, I had backed off from implementing something like this in the past because of the potential collateral bugs with a feature like this. But I've heard this issue brought up before and so it has been implemented. You can now ctrl+click to get rid of workers/building that are not needed anymore.
